services:
   redis: 
     image: redislabs/redismod
     ports:
       - '6000:6000' 
   web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
